//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media()
        {
            this.ActivityFile = new HashSet<ActivityFile>();
        }
    
        public int MID { get; set; }
        public int Category { get; set; }
        public int LinkType { get; set; }
        public string Yearx { get; set; }
        public string Title { get; set; }
        public string FullPath { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityFile> ActivityFile { get; set; }
    }
}
